### ISSUE TITLE
Incompatible with CKEditor 4.5.3 in Chrome

### ISSUE THREAD

**Issue by sabengry** [w8tcha/CKEditor-CodeMirror-Plugin#96]
Steps to reproduce:
    Install Codemirror plugin
    Open CKEditor in Chrome
    Write content into CKEditor
    Click on source mode 

Expected result:
Source mode should be opened with html contents of the editor highlighted.

Actual result:
Contents are deleted and CKEditor errors out. No response from CKEditor after this.
Other details (browser, OS, CKEditor version, installed plugins)

Works in FireFox 40 and 41. 
Works in IE 11. 
Fails in Chrome 45. 
Fails in CKEditor version 4.5.3 
Worked in CKEditor version 4.3.3 (just upgraded from this)

Error message: Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu') contains HTML space characters, which are not valid in tokens. ckeditor.js:79

**Comment by w8tcha** [comment]
Already fixed with commit c4a2019600b46a1be334dc65a47893b219c92e83

**Comment by sabengry** [comment]
That's the version of the code I am running now. I don't know what version was installed at first as I didn't do the install.  I installed this version after first encountering the error. The update did not fix the issue though. I have had to remove codemirror from my production servers.
